const dummy = {
    data: {
        title: "박스오피스",
        description: "홍길동님의 컬렉션",
        poster: process.env.PUBLIC_URL + "/images/1.jpg",
        list: [
            {
                rank: 1,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/1.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
            {
                rank: 2,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/2.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
            {
                rank: 3,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/3.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
            {
                rank: 4,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/4.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
            {
                rank: 5,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/5.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
            {
                rank: 6,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/6.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
            {
                rank: 7,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/1.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
            {
                rank: 8,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/2.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
            {
                rank: 9,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/3.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
            {
                rank: 10,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/4.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
            {
                rank: 11,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/5.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
            {
                rank: 12,
                mainTitle: "도굴",
                posterImagePath: process.env.PUBLIC_URL + "/images/6.jpg",
                year: 1996,
                nation: "미국",
                score: 4.123,
                rate: "5.5",
            },
        ],
    },
};

export default dummy;
